# Generated by Django 4.2.29 on 2026-04-05 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0037_match_game_match_fin_pre_3ae1a9_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournoi',
            name='date_lancement',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tournoi',
            name='status',
            field=models.CharField(choices=[('EA', 'En Attente'), ('EC', 'En Cours'), ('CM', 'Creation Des Matchs'), ('FI', 'Fini'), ('ER', 'Erreur'), ('LP', 'Lancement Programmé')], default='EA', max_length=2),
        ),
    ]
