# Generated by Django 4.2.29 on 2026-04-07 10:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0038_alter_tournoi_date_lancement_alter_tournoi_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='champion',
            name='nom',
            field=models.CharField(max_length=32, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z-_0-9]*$', 'Les seuls caractères valides sont les lettres, les chiffres, - et _.')]),
        ),
    ]
